#!/bin/sh

storage_program="/usr/libexec/iot-app-prepare-data-storage"

start() {
	printf "Preparing persistent data storage: "
	if "$storage_program"; then
		echo "OK"
	else
		echo "FAIL"
		return 1
	fi
}

stop() {
	if grep -q ' /data ' /proc/mounts; then
		umount /data
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
