#!/bin/bash

# Buildroot runs this script after it has created the Linux root filesystem,
# kernel, device trees, and Raspberry Pi firmware files. The script combines
# those files into the final sdcard.img written to the microSD card.
# iot_rpi4_defconfig registers it through BR2_ROOTFS_POST_IMAGE_SCRIPT. It is
# not normally run by hand because it depends on paths supplied by Buildroot.
#
# The standard Raspberry Pi image layout is not enough for this project
# because IoT App also needs a persistent /data partition. This script:
#
#   1. reads the configured root and initial data partition sizes;
#   2. finds the files needed in the Raspberry Pi boot partition;
#   3. fills in genimage.cfg.in with those files and sizes;
#   4. creates an empty ext4 filesystem labelled iot-data; and
#   5. runs genimage to assemble boot, root, and data partitions into
#      sdcard.img.
#
# The data partition starts small so sdcard.img stays compact. During the
# first boot, iot-app-prepare-data-storage expands it to the end of the card.
#
# Buildroot post-image script reference:
# https://buildroot.org/downloads/manual/manual.html#rootfs-custom

# Stop immediately if a command fails. A partial image must not be reported as
# a successful build.
set -e

# Buildroot provides BASE_DIR, BINARIES_DIR, BUILD_DIR, and HOST_DIR when it
# starts a post-image script:
#
#   BASE_DIR     is the selected Buildroot output directory.
#   BINARIES_DIR contains rootfs.ext4, firmware, the kernel, and final images.
#   BUILD_DIR    contains temporary package and image-building files.
#   HOST_DIR     contains host tools built by Buildroot, such as mkfs.ext4.
board_directory="$(dirname "$0")"
storage_layout_file="${BASE_DIR}/iot-app-storage-layout.conf"
generated_genimage_configuration="${BINARIES_DIR}/genimage-iot-app.cfg"
genimage_temporary_directory="${BUILD_DIR}/genimage-iot-app.tmp"

# make buildroot-prepare writes this file from storage_layout.conf. The
# fallback values also allow Buildroot to call this script directly.
if [ -f "$storage_layout_file" ]; then
	# This file is generated by make buildroot-prepare.
	# shellcheck disable=SC1090
	source "$storage_layout_file"
else
	ROOT_PARTITION_SIZE_MIB=1024
	DATA_PARTITION_BOOTSTRAP_SIZE_MIB=64
fi

# Build the list copied into boot.vfat. Raspberry Pi firmware files and device
# trees are generated under BINARIES_DIR. config.txt tells us which kernel file
# the firmware will load, so that kernel is added to the same list.
boot_files=()
for boot_file in "${BINARIES_DIR}"/*.dtb "${BINARIES_DIR}"/rpi-firmware/*; do
	boot_files+=("${boot_file#${BINARIES_DIR}/}")
done

kernel_file="$(sed -n 's/^kernel=//p' "${BINARIES_DIR}/rpi-firmware/config.txt")"
boot_files+=("$kernel_file")

# Create the real genimage configuration. The generated copy is kept in the
# images directory so the exact partition layout can be inspected after a
# build. The boot placeholder expands to several lines, so a normal loop is
# used instead of placing that multi-line value inside one sed command.
while IFS= read -r template_line; do
	if [ "$template_line" = "#BOOT_FILES#" ]; then
		printf '\t\t\t"%s",\n' "${boot_files[@]}"
		continue
	fi

	template_line="${template_line//@ROOT_PARTITION_SIZE_MIB@/${ROOT_PARTITION_SIZE_MIB}}"
	template_line="${template_line//@DATA_PARTITION_BOOTSTRAP_SIZE_MIB@/${DATA_PARTITION_BOOTSTRAP_SIZE_MIB}}"
	printf '%s\n' "$template_line"
done < "${board_directory}/genimage.cfg.in" > "$generated_genimage_configuration"

# Create the initial data filesystem consumed by genimage. The iot-data label
# lets the first-boot script verify that it found the correct partition before
# resizing it.
data_filesystem_image="${BINARIES_DIR}/data.ext4"
truncate --size "${DATA_PARTITION_BOOTSTRAP_SIZE_MIB}M" "$data_filesystem_image"
"${HOST_DIR}/sbin/mkfs.ext4" -F -q -L iot-data "$data_filesystem_image"

# genimage only assembles files that already exist. An empty root directory
# avoids copying the complete target filesystem into its work directory.
empty_root_directory="$(mktemp -d)"
trap 'rm -rf "$empty_root_directory"' EXIT
rm -rf "$genimage_temporary_directory"

# genimage reads boot.vfat, rootfs.ext4, and data.ext4 from BINARIES_DIR. It
# writes the finished sdcard.img back to the same directory.
genimage \
	--rootpath "$empty_root_directory" \
	--tmppath "$genimage_temporary_directory" \
	--inputpath "$BINARIES_DIR" \
	--outputpath "$BINARIES_DIR" \
	--config "$generated_genimage_configuration"
